# Generated by Django 5.2.7 on 2025-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('calls_count', models.IntegerField(default=0)),
                ('leads_count', models.IntegerField(default=0)),
                ('effective_calls', models.IntegerField(default=0)),
                ('effective_leads', models.IntegerField(default=0)),
                ('non_trash_leads', models.IntegerField(default=0)),
                ('approved_leads', models.IntegerField(default=0)),
                ('buyout_count', models.IntegerField(default=0)),
                ('effective_rate', models.FloatField(default=0.0)),
                ('effective_percent', models.FloatField(default=0.0)),
                ('avg_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kpi_data',
                'indexes': [models.Index(fields=['category', 'date_from'], name='kpi_data_categor_88c5c6_idx'), models.Index(fields=['offer_name', 'operator_name'], name='kpi_data_offer_n_73fb47_idx')],
            },
        ),
    ]
